- name: Overwrite Default Variables
  ansible.builtin.set_fact:
    valheim_settings: '{{ default_valheim_settings | ansible.builtin.combine(valheim_settings | default([])) }}'
- name: Stop Valheim
  ansible.builtin.import_role: 
    name: valheim
    tasks_from: stop_valheim
    public: true
- name: Install TMux
  ansible.builtin.dnf:
    name: tmux
  become: true
- name: Install x86_64 Emulator
  ansible.builtin.import_role: 
    name: x86_64_emulator
    tasks_from: install_x86_64_emulator
    public: true
- name: Install Valheim Dedicated Server
  ansible.builtin.shell:
    cmd: /home/{{ ansible_user }}/src/FEX/build/Bin/FEXBash "/home/{{ ansible_user}}/bin/steamcmd/steamcmd.sh +force_install_dir /home/{{ ansible_user }}/bin/valheim_server +@sSteamCmdForcePlatformType linux +login anonymous +app_update 896660 validate +quit"
- name: Set Valheim Settings
  ansible.builtin.template:
    src: start_server.sh.j2
    dest: /home/{{ ansible_user }}/bin/valheim_server/start_server.sh
- name: Open Firewall TCP
  ansible.posix.firewalld:
    port: '{{ valheim_settings.server_port }}-{{ valheim_settings.server_port + 2}}/tcp'
    permanent: true
    state: enabled
    immediate: true
  become: true
- name: Open Firewall UDP
  ansible.posix.firewalld:
    port: '{{ valheim_settings.server_port }}-{{ valheim_settings.server_port + 2}}/udp'
    permanent: true
    state: enabled
    immediate: true
  become: true
- name: Load Valheim Service
  ansible.builtin.template:
    src: valheim.service.j2
    dest: /etc/systemd/system/valheim.service
  become: true
- name: Start Valheim
  ansible.builtin.import_role: 
    name: valheim
    tasks_from: start_valheim
    public: true
